# check=skip=JSONArgsRecommended
FROM debian:trixie

RUN dpkg --add-architecture arm64
RUN apt update && apt dist-upgrade -y
RUN apt install -y \
    g++-aarch64-linux-gnu \
    libc6-dev-arm64-cross \
    build-essential \
    pkg-config \
    libbz2-dev \
    ca-certificates \
    nodejs npm \
    xdg-utils \
    qemu-user-static \
    binfmt-support \
    lsb-release \
    curl

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y 
RUN $HOME/.cargo/bin/rustup target add aarch64-unknown-linux-gnu
RUN $HOME/.cargo/bin/cargo install tauri-cli --git https://github.com/tauri-apps/tauri
WORKDIR /app

RUN apt install -y --no-install-recommends \
    libssl-dev:arm64 \
    curl:arm64 \
    wget:arm64 \
    libgtk-3-dev:arm64 \
    patchelf:arm64 \
    librsvg2-dev:arm64 \
    libwebkit2gtk-4.1-dev:arm64

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
    CC_aarch64-unknown-linux-gnu=aarch64-linux-gnu-gcc \
    CXX_aarch64-unknown-linux-gnu=aarch64-linux-gnu-g++ \
    PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig \
    PKG_CONFIG_ALLOW_CROSS=1
WORKDIR /app/src-tauri

CMD ["bash", "-ec", "cd /app; npm ci --ignore-scripts; cd /app/src-tauri; /root/.cargo/bin/cargo tauri build --target aarch64-unknown-linux-gnu --bundles deb --verbose; owner_group=$(stat -c '%u:%g' /app); chown -R \"$owner_group\" /app/dist /app/src-tauri/target"]
