FROM ubuntu:plucky

RUN dpkg --add-architecture arm64
RUN echo "\
# For amd64 (native architecture) \n\
deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ plucky main restricted universe multiverse \n\
deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ plucky-updates main restricted universe multiverse \n\
deb [arch=amd64] http://security.ubuntu.com/ubuntu/ plucky-security main restricted universe multiverse \n\
# For arm64 (foreign architecture) \n\
deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ plucky main restricted universe multiverse \n\
deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ plucky-updates main restricted universe multiverse \n\
deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ plucky-security main restricted universe multiverse \n\
"> /etc/apt/sources.list
RUN rm -rvf /etc/apt/sources.list.d/* 

RUN apt update && apt dist-upgrade -y
RUN apt install -y --no-install-recommends \
                   g++-aarch64-linux-gnu \
                   libc6-dev-arm64-cross \
                   libssl-dev:arm64 \
                   libwebkit2gtk-4.1-dev:arm64 \
                   build-essential \
                   curl:arm64 \
                   wget:arm64 \
                   libgtk-3-dev:arm64 \
                   patchelf:arm64 \
                   librsvg2-dev:arm64 \
                   pkg-config \
                   libbz2-dev \
                   ca-certificates \
                   nodejs npm 
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y 
RUN $HOME/.cargo/bin/rustup target add aarch64-unknown-linux-gnu
RUN $HOME/.cargo/bin/cargo install tauri-cli --git https://github.com/tauri-apps/tauri
WORKDIR /app

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
    CC_aarch64-unknown-linux-gnu=aarch64-linux-gnu-gcc \
    CXX_aarch64-unknown-linux-gnu=aarch64-linux-gnu-g++ \
    PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig \
    PKG_CONFIG_ALLOW_CROSS=1
WORKDIR /app/src-tauri
RUN apt install -y nodejs npm 
RUN apt install -y xdg-utils
CMD ["/root/.cargo/bin/cargo" ,"tauri",  "build", "--target", "aarch64-unknown-linux-gnu","--bundles", "deb", "--verbose"]
