on:
  workflow_call:

jobs:
  build_on_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18
      # Step 3
      - name: Check code format
        run: npx prettier --config .prettierrc ./src/**/*.{tsx,ts} --check
      # Step 4
      - name: Install dependencies
        run: npm install
      # Step 5
      - name: Build Application and Run unit Test
        run: exit 0
