on:
  workflow_call:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      # Step 3
      - name: Check code format
        run: npx prettier --config .prettierrc ./src/**/*.{tsx,ts} --check
      # Step 4
      - name: Install dependencies
        run: npm install
      # Step 5
      - name: Build Application and Run unit Test
        run: exit 0