on:
  workflow_call:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      # Step 3
      - name: Install dependencies
        run: npm install
      # Step 4
      - name: Check code format
        run: npm run format:check
      # Step 5
      - name: Check types
        run: npm run types
      # Step 5
      - name: Static analysis
        run: npm run lint
      # Step 6
      - name: Build Application and Run unit Test
        run: exit 0
        if: false
