name: Pre-release Alpha version
on:
  push:
    branches:
      - alpha
jobs:
  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
  set-release-version:
    needs: continuous-integration
    uses: ./.github/workflows/set-release-version.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}