on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      DISTRIBUTION_FOLDER:
        required: true
      S3_BUCKET:
        required: true
      PUBLISH_BRANCH:
        required: true
jobs:
  publish_on_linux:
    runs-on: meticulous-runner
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ secrets.PUBLISH_BRANCH }}
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: install dependencies
        run: npm i
      - name: publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DISTRIBUTION_FOLDER: ${{ secrets.DISTRIBUTION_FOLDER }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: npm run publish