on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  set-release-version:
    name: Set release version
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Disable "include administrators" branch protection
        id: disable_include_admins
        uses: benjefferies/branch-protection-bot@1.0.8
        if: always()
        with:
          access_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref_name }}
          enforce_admins: false

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --branches ${{ github.ref_name }}

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@1.0.8
        if: always()
        with:
          access_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref_name }}
          enforce_admins: ${{ steps.disable_include_admins.outputs.initial_status }}

