name: Verify pull request base branch

on:
  pull_request:
    branches:
      - master
jobs:
  verify-base-branch:
    name: Verify base branch is beta
    runs-on: ubuntu-20.04
    steps:
      - name: Check base branch
        if: github.head_ref != 'beta'
        run: exit 1
